export { postMatch } from './matches'
export { fetchSchedule, getMatchID, onlock } from './schedule'
export { postPrediction } from './prediction'
export { auth,logout } from './auth'
export { fetchUsers, getUsers, fetchPrediction } from './dashboard'
export { postResult, postPoints } from './result'